### ISSUE TITLE
[feature request] BotConfig.EnableAudio is required to be true for using SendFriendMessage/SendGroupMessage

### ISSUE THREAD

**Issue by EtherealAO** [KonataDev/Konata.Core#142]
**Describe features you've considered / 新功能描述**  
A clear and concise description of any features you've considered.  

BotConfig.EnableAudio is required to be true for using SendFriendMessage/SendGroupMessage, but it is false now by default. Is it better to set EnableAudio to true by default? Or give a warn when invoking them without EnableAudio? It took me 90 minutes to figure it out.

**Additional context / 附加资源**  
nope

**Comment by TheSnowfield** [comment]
I'm so sorry to hear about we had brought trouble to you.
In the current situation, we have no time to write docs for users cuz we're cost a lot of time on the development.

The reason that we default set `EnableAudio` to false is the audio codec is an additional function of the core,
If you hope to use the audio function you need to build the [libSilkCodec](https://github.com/KonataDev/libSilkCodec) library for the core, we do even not offer the binaries.

The warning you can figure it out in the main branch:
https://github.com/KonataDev/Konata.Core/blob/main/Konata.Core/Components/Logics/Model/MessagingLogic.cs#L355-L361
```c#
// Return false if audio configuration not enabled
if (!ConfigComponent.GlobalConfig.EnableAudio)
{
    Context.LogW(TAG, "The audio function is currently disabled. " +
                      "Lack of codec library.");
    return false;
}
```

So I guess the problem may caused while you create a `RecordChain`?
If you're using an mp3 to create a record chain, probably you can get the error.

**Comment by EtherealAO** [comment]
Yes i saw the warning, but can't associate it with SendFriendMessage, hope this issue can help the others
