### ISSUE TITLE
[bug report] 特殊字符无法解析

### ISSUE THREAD

**Issue by Nekoer** [KonataDev/Konata.Core#168]
**Environment / 环境**
用的develop源代码，win11 net60

**Expected behavior / 预期行为**
不论是群名称好友名称还是消息中，特殊符号无法解析，会转为？ 例如❄

能否告知在哪个文件里可以进行相关转码

**Comment by TheSnowfield** [comment]
emoji無法解析嗎

**Comment by Nekoer** [comment]
只有这种🌦❄无法解析

**Comment by TheSnowfield** [comment]
> 只有这种🌦❄无法解析

檢查過終端編碼了嗎? 顯示emoji需要終端UTF8或者寬字符支持

**Comment by Nekoer** [comment]
谢谢,确实是終端编码的问题
