### ISSUE TITLE
[bug report] 发送群消息循环

### ISSUE THREAD

**Issue by Nekoer** [KonataDev/Konata.Core#169]
**Environment / 环境**
Dev分支

Operating system information.
Window11

**Expected behavior / 预期行为**
发送群消息循环

**To Reproduce / 复现**
```
_bot.OnGroupMessage += (bot, e) => {
    bot.SendGroupMessage(e.GroupUin, e.Chain);
};
```

**Comment by TheSnowfield** [comment]
請嘗試按uin手動過濾bot自身發送的消息

**Comment by Nekoer** [comment]
了解,原因居然是这个
