### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by yanyunwu** [KonataDev/Konata.Core#173]
**Describe features you've considered / 新功能描述**  
A clear and concise description of any features you've considered.  
清晰明了地描述你希望实现的新功能

**Additional context / 附加资源**  
如果需要, 这里此上传截图或资源

我可以加入你们的组织吗

**Comment by TheSnowfield** [comment]
請查收電郵。

**Comment by yanyunwu** [comment]
收到了，你们有类似QQ群的交流平台吗

**Comment by TheSnowfield** [comment]
> 收到了，你们有类似QQ群的交流平台吗

https://t.me/konachan_wifi
