### ISSUE TITLE
[bug report] bot.GroupKickMember(groupUid, qqUid, true)引发异常

### ISSUE THREAD

**Issue by lepollo** [KonataDev/Konata.Core#203]
**Environment / 环境**
`Konata.Core`版本1.33

Operating system information.
操作系统相关信息：windows10

**Expected behavior / 预期行为**
bot.GroupKickMember(group, qq, true)，经检查groupuid和qquid均正确，bot有管理员权限，网络通畅，但程序返回异常
异常信息：TimeoutException: Don't be a pigeon. =(:3)z)_

代码：
        public static string Kict(uint group,List<uint> qqs)
        {
            if (qqs.Count == 0) return "无人可踢了";
            if (bot.GetGroupList().Result.Any(g => g.Uin == group) == false) return "我不在该群，没法踢人。";
            if (bot.GetGroupMemberInfo(group, bot.Uin).Result.Role != RoleType.Admin) return "我不是管理员，没法踢人。";
            int successcount=0,failcount = 0;
            try
            {
                foreach (var qq in qqs)
                {
                    if (bot.GroupKickMember(group, qq, true).Result) successcount++;
                    else failcount++;
                    Thread.Sleep(1000);
                }
            }
            catch (Exception err) { return $"踢人失败，原因:{err.Message}{NewLine}"; }
            return $"成功踢了{successcount}人，有{failcount}人没踢。";
        }

**Stack trace / 堆栈信息**
Paste the stack trace below.
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Don't be a pigeon. =(:3)z)_)
  Source=System.Private.CoreLib
  StackTrace:
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   在 QQBot.RunningBot.Kict(UInt32 group, List`1 qqs) 在 C:\QQbot\RunningBot.cs 中: 第 153 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
TimeoutException: Don't be a pigeon. =(:3)z)_

**Comment by TheSnowfield** [comment]
我看看
