### ISSUE TITLE
Nuget package id not available

### ISSUE THREAD

**Issue by TheSnowfield** [KonataDev/Konata.Core#71]
@yomunsam 
Sorry for the ping.
Could you please transfer the `Konata.Core` NuGet package id to us? 
Thank.

**Comment by TheSnowfield** [comment]
Here is the link [Konata.Core](https://www.nuget.org/packages/Konata.Core), please check it out.
This package is not published by the Konata Project official, 
but they have the conflict namespace. 
The project `Konata.Core` was created and started last year on Aug 3, 
but your package on NuGet is upload 7 months ago with an empty package and no repository url.
We hope it's a mistake.

**Comment by yomunsam** [comment]
您好我看您资料里有chinese就直接用汉语了
这个包是当时挖坑一半的项目，然后弃坑了就给都Unlisted了，
那么接下来需要怎么操作才能把这个包ID给到你们呢？

**Comment by TheSnowfield** [comment]
> 您好我看您资料里有chinese就直接用汉语了
> 这个包是当时挖坑一半的项目，然后弃坑了就给都Unlisted了，
> 那么接下来需要怎么操作才能把这个包ID给到你们呢？

可以使用
```bash
$ dotnet nuget delete Konata.Core x.x.x -s https://www.nuget.org/ -k YOUR_APIKEY
``` 
来删除包, 其中 `x.x.x` 是将要删除的版本, `YOUR_APIKEY` 为您的私有key

真心的感谢!

**Comment by yomunsam** [comment]
![image](https://user-images.githubusercontent.com/24813704/130565106-0dacc780-3835-4b07-a977-a453c4c34364.png)
这样应该可以了？

**Comment by TheSnowfield** [comment]
> ![image](https://user-images.githubusercontent.com/24813704/130565106-0dacc780-3835-4b07-a977-a453c4c34364.png)
> 这样应该可以了？

非常并且衷心的感激你的配合!
