### ISSUE TITLE
Record is not playable on iOS devices

### ISSUE THREAD

**Issue by TheSnowfield** [KonataDev/Konata.Core#82]

**Comment by takayama-lily** [comment]
看看
https://github.com/Mrs4s/go-cqhttp/issues/849
https://github.com/Mrs4s/go-cqhttp/issues/390

**Comment by TheSnowfield** [comment]
> 看看
> [Mrs4s/go-cqhttp#849](https://github.com/Mrs4s/go-cqhttp/issues/849)
> [Mrs4s/go-cqhttp#390](https://github.com/Mrs4s/go-cqhttp/issues/390)

較短的語音好像能夠播放, 所以感覺有可能跟這個關係不太大.
可以先mark一下.

**Comment by TheSnowfield** [comment]
Fixed, please see https://github.com/KonataDev/libSilkCodec/commit/16ac7b3d975066fa3b767133bb224cedccd1de97 
Closed.
