### ISSUE TITLE
[bug report] PutOicqRequestBody 写法纠正 大概...

### ISSUE THREAD

**Issue by o2e** [KonataDev/Konata.Core#97]
这里可以尝试写成这样，我没有window编译环境，无法保证能在这里正常运行。仅做一个小记录~ 😘
https://github.com/KonataDev/Konata.Core/blob/d2ea87076018fe125b92759637561a6c7b43a12c/Packets/Oicq/OicqRequest.cs#L68-L70

```java
PutByte(2);
PutByte(1);
PutBytes(randKey); 
PutUshortBE(305)
PutUshortBE(1);
```

**Comment by TheSnowfield** [comment]
konata.core是跨平台的， 你可以在受到支援的任意平台上(windows/gnu linux/macos)上使用dotnet編譯並運行。
